// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: code.jflex

package LexicalAndSyntacticAnalyzer.jflexandcupManagerUser;

import java_cup.runtime.Symbol;

import reports.ReportErrorInterpreter;
import reports.ReportingConstants;
import reports.TypeIntreprete;

import java.util.ArrayList;

import LexicalAndSyntacticAnalyzer.analyzer.Token;


@SuppressWarnings("fallthrough")
public class LexemaByMyParesUser implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\247\u0100"+
    "\10\u0500\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\2\1\4\2\22\0\1\1\1\3\1\4\5\0"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\12\15\1\16\1\0\1\17\1\20\1\21\1\22\1\0"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\2\0\1\34\1\35\1\36\1\37\1\40\1\0"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\2\0"+
    "\1\50\1\51\1\52\1\0\1\53\1\0\1\54\1\0"+
    "\1\55\1\56\1\57\1\60\2\0\1\61\2\0\1\62"+
    "\1\0\1\63\1\64\2\0\1\65\1\66\1\67\1\70"+
    "\1\71\1\0\1\72\1\0\1\73\1\74\1\1\1\75"+
    "\7\0\1\2\32\0\1\1\u01df\0\1\1\177\0\13\1"+
    "\22\0\1\76\12\0\2\2\5\0\1\1\57\0\1\1"+
    "\240\0\1\1\377\0\u0100\77";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\2\1\1\17\1\20\4\1\1\21\1\22\1\23\1\0"+
    "\1\24\20\0\1\25\1\26\1\27\30\0\1\12\15\0"+
    "\1\30\24\0\1\31\55\0\1\32\13\0\1\33\3\0"+
    "\1\34\17\0\1\35\3\0\1\36\6\0\1\37\2\0"+
    "\1\40\10\0\1\41\24\0\1\42\6\0\1\43\7\0"+
    "\1\44\1\0\1\45\17\0\1\46\5\0\1\47\10\0"+
    "\1\50\31\0\1\51\27\0\1\52\15\0\1\53\11\0"+
    "\1\54\3\0\1\55\1\56\12\0\1\57\12\0\1\60"+
    "\6\0\1\61\1\62\6\0\1\63\1\0\1\64\3\0"+
    "\1\65\2\0\1\66\3\0\1\67\1\0\1\70\3\0"+
    "\1\71\5\0\1\72\1\73\4\0\1\74\3\0\1\75"+
    "\1\76\2\0\1\77";

  private static int [] zzUnpackAction() {
    int [] result = new int[434];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\300\0\u0100\0\100\0\100\0\100"+
    "\0\100\0\100\0\100\0\100\0\u0140\0\100\0\u0180\0\100"+
    "\0\100\0\u01c0\0\u0200\0\100\0\100\0\u0240\0\u0280\0\u02c0"+
    "\0\u0300\0\100\0\100\0\100\0\u0340\0\100\0\u0380\0\u03c0"+
    "\0\u0400\0\u0440\0\u0480\0\u04c0\0\u0500\0\u0540\0\u0580\0\u05c0"+
    "\0\u0600\0\u0640\0\u0680\0\u06c0\0\u0700\0\u0740\0\u0780\0\100"+
    "\0\100\0\u07c0\0\u0800\0\u0840\0\u0880\0\u08c0\0\u0900\0\u0940"+
    "\0\u0980\0\u09c0\0\u0a00\0\u0a40\0\u0a80\0\u0ac0\0\u0b00\0\u0b40"+
    "\0\u0b80\0\u0bc0\0\u0c00\0\u0c40\0\u0c80\0\u0cc0\0\u0d00\0\u0d40"+
    "\0\u0d80\0\u0740\0\u0dc0\0\u0e00\0\u0e40\0\u0e80\0\u0ec0\0\u0f00"+
    "\0\u0f40\0\u0f80\0\u0fc0\0\u1000\0\u1040\0\u1080\0\u10c0\0\100"+
    "\0\u1100\0\u1140\0\u1180\0\u11c0\0\u1200\0\u1240\0\u1280\0\u12c0"+
    "\0\u1300\0\u1340\0\u1380\0\u13c0\0\u1400\0\u1440\0\u1480\0\u14c0"+
    "\0\u1500\0\u1540\0\u1580\0\u15c0\0\100\0\u1600\0\u1640\0\u1680"+
    "\0\u16c0\0\u1700\0\u1740\0\u1780\0\u17c0\0\u1800\0\u1840\0\u1880"+
    "\0\u18c0\0\u1900\0\u1940\0\u1980\0\u19c0\0\u1a00\0\u1a40\0\u1a80"+
    "\0\u1ac0\0\u1b00\0\u1b40\0\u1b80\0\u1bc0\0\u1c00\0\u1c40\0\u1c80"+
    "\0\u1cc0\0\u1d00\0\u1d40\0\u1d80\0\u1dc0\0\u1e00\0\u1e40\0\u1e80"+
    "\0\u1ec0\0\u1f00\0\u1f40\0\u1f80\0\u1fc0\0\u2000\0\u2040\0\u2080"+
    "\0\u20c0\0\u2100\0\100\0\u2140\0\u2180\0\u21c0\0\u2200\0\u2240"+
    "\0\u2280\0\u22c0\0\u2300\0\u2340\0\u2380\0\u23c0\0\100\0\u2400"+
    "\0\u2440\0\u2480\0\100\0\u24c0\0\u2500\0\u2540\0\u2580\0\u25c0"+
    "\0\u2600\0\u2640\0\u2680\0\u26c0\0\u2700\0\u2740\0\u2780\0\u27c0"+
    "\0\u2800\0\u2840\0\100\0\u2880\0\u28c0\0\u2900\0\100\0\u2940"+
    "\0\u2980\0\u29c0\0\u2a00\0\u2a40\0\u2a80\0\100\0\u2ac0\0\u2b00"+
    "\0\100\0\u2b40\0\u2b80\0\u2bc0\0\u2c00\0\u2c40\0\u2c80\0\u2cc0"+
    "\0\u2d00\0\100\0\u2d40\0\u2d80\0\u2dc0\0\u2e00\0\u2e40\0\u2e80"+
    "\0\u2ec0\0\u2f00\0\u2f40\0\u2f80\0\u2fc0\0\u3000\0\u3040\0\u3080"+
    "\0\u30c0\0\u3100\0\u3140\0\u3180\0\u31c0\0\u3200\0\100\0\u3240"+
    "\0\u3280\0\u32c0\0\u3300\0\u3340\0\u3380\0\100\0\u33c0\0\u3400"+
    "\0\u3440\0\u3480\0\u34c0\0\u3500\0\u3540\0\100\0\u3580\0\100"+
    "\0\u35c0\0\u3600\0\u3640\0\u3680\0\u36c0\0\u3700\0\u3740\0\u3780"+
    "\0\u37c0\0\u3800\0\u3840\0\u3880\0\u38c0\0\u3900\0\u3940\0\100"+
    "\0\u3980\0\u39c0\0\u3a00\0\u3a40\0\u3a80\0\100\0\u3ac0\0\u3b00"+
    "\0\u3b40\0\u3b80\0\u3bc0\0\u3c00\0\u3c40\0\u3c80\0\100\0\u3cc0"+
    "\0\u3d00\0\u3d40\0\u3d80\0\u3dc0\0\u3e00\0\u3e40\0\u3e80\0\u3ec0"+
    "\0\u3f00\0\u3f40\0\u3f80\0\u3fc0\0\u4000\0\u4040\0\u4080\0\u40c0"+
    "\0\u4100\0\u4140\0\u4180\0\u41c0\0\u4200\0\u4240\0\u4280\0\u42c0"+
    "\0\100\0\u4300\0\u4340\0\u4380\0\u43c0\0\u4400\0\u4440\0\u4480"+
    "\0\u44c0\0\u4500\0\u4540\0\u4580\0\u45c0\0\u4600\0\u4640\0\u4680"+
    "\0\u46c0\0\u4700\0\u4740\0\u4780\0\u47c0\0\u4800\0\u4840\0\u4880"+
    "\0\100\0\u48c0\0\u4900\0\u4940\0\u4980\0\u49c0\0\u4a00\0\u4a40"+
    "\0\u4a80\0\u4ac0\0\u4b00\0\u4b40\0\u4b80\0\u4bc0\0\100\0\u4c00"+
    "\0\u4c40\0\u4c80\0\u4cc0\0\u4d00\0\u4d40\0\u4d80\0\u4dc0\0\u4e00"+
    "\0\100\0\u4e40\0\u4e80\0\u4ec0\0\100\0\100\0\u4f00\0\u4f40"+
    "\0\u4f80\0\u4fc0\0\u5000\0\u5040\0\u5080\0\u50c0\0\u5100\0\u5140"+
    "\0\100\0\u5180\0\u51c0\0\u5200\0\u5240\0\u5280\0\u52c0\0\u5300"+
    "\0\u5340\0\u5380\0\u53c0\0\100\0\u5400\0\u5440\0\u5480\0\u54c0"+
    "\0\u5500\0\u5540\0\100\0\100\0\u5580\0\u55c0\0\u5600\0\u5640"+
    "\0\u5680\0\u56c0\0\100\0\u5700\0\100\0\u5740\0\u5780\0\u57c0"+
    "\0\100\0\u5800\0\u5840\0\u5880\0\u58c0\0\u5900\0\u5940\0\100"+
    "\0\u5980\0\100\0\u59c0\0\u5a00\0\u5a40\0\100\0\u5a80\0\u5ac0"+
    "\0\u5b00\0\u5b40\0\u5b80\0\100\0\100\0\u5bc0\0\u5c00\0\u5c40"+
    "\0\u5c80\0\100\0\u5cc0\0\u5d00\0\u5d40\0\100\0\100\0\u5d80"+
    "\0\u5dc0\0\100";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[434];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\2\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\5\2\1\23\17\2\1\24\1\2\1\25"+
    "\5\2\1\26\4\2\1\27\3\2\1\30\1\31\1\2"+
    "\1\32\1\33\1\2\102\0\2\3\116\0\1\34\56\0"+
    "\4\35\1\36\10\35\1\37\5\35\1\40\1\35\1\41"+
    "\1\42\1\43\1\44\2\35\1\45\1\35\1\46\1\47"+
    "\1\50\1\51\1\52\1\35\1\53\1\54\4\35\1\55"+
    "\26\35\13\0\1\56\1\0\1\15\65\0\1\57\16\0"+
    "\1\60\76\0\1\61\105\0\1\62\131\0\1\63\75\0"+
    "\1\64\77\0\1\65\106\0\1\66\11\0\4\35\1\36"+
    "\44\35\1\55\32\35\1\36\10\35\1\67\33\35\1\55"+
    "\32\35\1\36\24\35\1\70\17\35\1\55\32\35\1\36"+
    "\27\35\1\71\2\35\1\72\11\35\1\55\32\35\1\36"+
    "\16\35\1\73\25\35\1\55\32\35\1\36\27\35\1\74"+
    "\14\35\1\55\32\35\1\36\26\35\1\75\15\35\1\55"+
    "\32\35\1\36\21\35\1\76\7\35\1\77\12\35\1\55"+
    "\32\35\1\36\32\35\1\100\11\35\1\55\32\35\1\36"+
    "\32\35\1\101\4\35\1\102\4\35\1\55\32\35\1\36"+
    "\33\35\1\103\10\35\1\55\32\35\1\36\16\35\1\104"+
    "\25\35\1\55\32\35\1\36\22\35\1\105\21\35\1\55"+
    "\32\35\1\36\22\35\1\106\3\35\1\107\5\35\1\110"+
    "\7\35\1\55\32\35\1\36\35\35\1\111\6\35\1\55"+
    "\30\35\1\0\74\35\16\0\1\112\74\0\1\113\112\0"+
    "\1\114\135\0\1\115\70\0\1\116\110\0\1\117\76\0"+
    "\1\120\13\0\4\35\1\36\10\35\1\121\33\35\1\55"+
    "\32\35\1\36\34\35\1\122\7\35\1\55\32\35\1\36"+
    "\16\35\1\123\25\35\1\55\32\35\1\36\27\35\1\124"+
    "\14\35\1\55\32\35\1\36\36\35\1\125\5\35\1\55"+
    "\32\35\1\36\26\35\1\126\15\35\1\55\32\35\1\36"+
    "\27\35\1\127\14\35\1\55\32\35\1\130\44\35\1\55"+
    "\1\35\1\131\30\35\1\36\21\35\1\132\13\35\1\133"+
    "\6\35\1\55\32\35\1\36\21\35\1\134\22\35\1\55"+
    "\32\35\1\36\30\35\1\135\13\35\1\55\32\35\1\36"+
    "\22\35\1\136\21\35\1\55\32\35\1\36\20\35\1\137"+
    "\23\35\1\55\32\35\1\36\34\35\1\140\1\141\6\35"+
    "\1\55\32\35\1\36\35\35\1\142\6\35\1\55\32\35"+
    "\1\36\30\35\1\143\11\35\1\144\1\35\1\55\32\35"+
    "\1\36\22\35\1\145\21\35\1\55\32\35\1\36\26\35"+
    "\1\146\15\35\1\55\32\35\1\36\37\35\1\147\4\35"+
    "\1\55\26\35\12\0\1\150\117\0\1\151\120\0\1\152"+
    "\106\0\1\153\103\0\1\154\74\0\1\155\14\0\4\35"+
    "\1\36\10\35\1\156\33\35\1\55\32\35\1\36\22\35"+
    "\1\157\21\35\1\55\32\35\1\36\35\35\1\160\6\35"+
    "\1\55\32\35\1\36\37\35\1\161\4\35\1\55\32\35"+
    "\1\36\32\35\1\162\11\35\1\55\32\35\1\36\30\35"+
    "\1\163\13\35\1\55\32\35\1\36\16\35\1\164\25\35"+
    "\1\55\32\35\1\36\36\35\1\165\5\35\1\55\32\35"+
    "\1\36\26\35\1\166\15\35\1\55\32\35\1\36\36\35"+
    "\1\167\5\35\1\55\32\35\1\36\26\35\1\170\15\35"+
    "\1\55\32\35\1\36\17\35\1\171\24\35\1\55\32\35"+
    "\1\36\40\35\1\172\3\35\1\55\32\35\1\36\26\35"+
    "\1\173\15\35\1\55\32\35\1\36\16\35\1\174\25\35"+
    "\1\55\32\35\1\36\35\35\1\175\6\35\1\55\32\35"+
    "\1\36\33\35\1\176\10\35\1\55\32\35\1\36\16\35"+
    "\1\177\25\35\1\55\32\35\1\36\36\35\1\200\5\35"+
    "\1\55\32\35\1\36\30\35\1\201\13\35\1\55\32\35"+
    "\1\36\40\35\1\202\3\35\1\55\32\35\1\36\16\35"+
    "\1\203\25\35\1\55\26\35\12\150\1\204\65\150\23\0"+
    "\1\205\142\0\1\206\72\0\1\207\77\0\1\210\16\0"+
    "\4\35\1\36\5\35\1\211\36\35\1\55\32\35\1\36"+
    "\24\35\1\212\17\35\1\55\32\35\1\36\22\35\1\213"+
    "\21\35\1\55\32\35\1\36\30\35\1\214\13\35\1\55"+
    "\32\35\1\36\35\35\1\215\6\35\1\55\32\35\1\36"+
    "\26\35\1\216\15\35\1\55\32\35\1\36\35\35\1\217"+
    "\6\35\1\55\32\35\1\36\34\35\1\220\7\35\1\55"+
    "\32\35\1\36\20\35\1\221\23\35\1\55\32\35\1\36"+
    "\26\35\1\222\15\35\1\55\32\35\1\36\23\35\1\223"+
    "\20\35\1\55\32\35\1\36\34\35\1\224\7\35\1\55"+
    "\32\35\1\36\16\35\1\225\13\35\1\226\11\35\1\55"+
    "\32\35\1\36\32\35\1\227\11\35\1\55\32\35\1\36"+
    "\30\35\1\230\13\35\1\55\32\35\1\36\41\35\1\231"+
    "\2\35\1\55\32\35\1\36\37\35\1\232\4\35\1\55"+
    "\32\35\1\233\44\35\1\55\32\35\1\36\32\35\1\234"+
    "\11\35\1\55\32\35\1\36\33\35\1\235\10\35\1\55"+
    "\32\35\1\36\26\35\1\236\15\35\1\55\32\35\1\36"+
    "\34\35\1\237\7\35\1\55\26\35\12\150\1\240\65\150"+
    "\53\0\1\241\110\0\1\242\106\0\1\243\70\0\1\244"+
    "\13\0\4\35\1\36\10\35\1\245\33\35\1\55\32\35"+
    "\1\36\16\35\1\246\25\35\1\55\32\35\1\247\44\35"+
    "\1\55\32\35\1\36\31\35\1\250\12\35\1\55\32\35"+
    "\1\36\44\35\1\55\1\35\1\251\30\35\1\36\31\35"+
    "\1\252\12\35\1\55\32\35\1\253\44\35\1\55\32\35"+
    "\1\36\26\35\1\254\15\35\1\55\32\35\1\36\22\35"+
    "\1\255\21\35\1\55\32\35\1\36\36\35\1\256\5\35"+
    "\1\55\32\35\1\36\26\35\1\257\15\35\1\55\32\35"+
    "\1\36\22\35\1\260\21\35\1\55\32\35\1\36\44\35"+
    "\1\55\1\35\1\261\30\35\1\36\44\35\1\55\1\35"+
    "\1\262\30\35\1\36\31\35\1\263\12\35\1\55\32\35"+
    "\1\36\22\35\1\264\21\35\1\55\32\35\1\36\32\35"+
    "\1\265\11\35\1\55\32\35\1\36\22\35\1\266\21\35"+
    "\1\55\32\35\1\36\44\35\1\55\1\35\1\267\30\35"+
    "\1\36\32\35\1\270\11\35\1\55\32\35\1\36\16\35"+
    "\1\271\25\35\1\55\32\35\1\36\26\35\1\272\15\35"+
    "\1\55\26\35\12\150\1\240\6\150\1\273\56\150\25\0"+
    "\1\274\134\0\1\275\71\0\1\276\106\0\1\277\14\0"+
    "\4\35\1\36\10\35\1\300\33\35\1\55\32\35\1\36"+
    "\34\35\1\301\7\35\1\55\32\35\1\36\16\35\1\302"+
    "\25\35\1\55\32\35\1\36\37\35\1\303\4\35\1\55"+
    "\32\35\1\36\16\35\1\304\25\35\1\55\32\35\1\36"+
    "\40\35\1\305\3\35\1\55\32\35\1\306\44\35\1\55"+
    "\32\35\1\36\37\35\1\307\4\35\1\55\32\35\1\36"+
    "\20\35\1\310\23\35\1\55\32\35\1\311\44\35\1\55"+
    "\32\35\1\36\36\35\1\312\5\35\1\55\32\35\1\36"+
    "\33\35\1\313\10\35\1\55\32\35\1\36\22\35\1\314"+
    "\21\35\1\55\32\35\1\36\36\35\1\315\5\35\1\55"+
    "\32\35\1\36\34\35\1\316\7\35\1\55\32\35\1\36"+
    "\35\35\1\317\6\35\1\55\32\35\1\36\40\35\1\320"+
    "\3\35\1\55\32\35\1\36\44\35\1\55\1\35\1\321"+
    "\30\35\1\322\44\35\1\55\32\35\1\36\32\35\1\323"+
    "\11\35\1\55\26\35\41\0\1\324\117\0\1\325\103\0"+
    "\1\326\12\0\4\35\1\36\5\35\1\327\36\35\1\55"+
    "\32\35\1\36\44\35\1\55\1\35\1\330\30\35\1\36"+
    "\35\35\1\331\6\35\1\55\32\35\1\36\35\35\1\332"+
    "\6\35\1\55\32\35\1\36\34\35\1\333\7\35\1\55"+
    "\32\35\1\36\26\35\1\334\15\35\1\55\32\35\1\36"+
    "\20\35\1\335\23\35\1\55\32\35\1\36\16\35\1\336"+
    "\25\35\1\55\32\35\1\36\34\35\1\337\7\35\1\55"+
    "\32\35\1\36\16\35\1\340\25\35\1\55\32\35\1\36"+
    "\35\35\1\341\6\35\1\55\32\35\1\36\34\35\1\342"+
    "\7\35\1\55\32\35\1\36\21\35\1\343\22\35\1\55"+
    "\32\35\1\36\36\35\1\344\5\35\1\55\32\35\1\36"+
    "\26\35\1\345\15\35\1\55\32\35\1\36\33\35\1\346"+
    "\10\35\1\55\32\35\1\347\44\35\1\55\1\35\1\350"+
    "\24\35\27\0\1\351\125\0\1\352\75\0\1\353\24\0"+
    "\4\35\1\36\10\35\1\354\33\35\1\55\32\35\1\36"+
    "\20\35\1\355\23\35\1\55\32\35\1\356\44\35\1\55"+
    "\32\35\1\36\37\35\1\357\4\35\1\55\32\35\1\36"+
    "\44\35\1\55\1\35\1\360\30\35\1\36\16\35\1\361"+
    "\25\35\1\55\32\35\1\36\26\35\1\362\15\35\1\55"+
    "\32\35\1\36\34\35\1\363\7\35\1\55\32\35\1\36"+
    "\26\35\1\364\15\35\1\55\32\35\1\36\35\35\1\365"+
    "\6\35\1\55\32\35\1\366\44\35\1\55\32\35\1\36"+
    "\32\35\1\367\11\35\1\55\32\35\1\370\44\35\1\55"+
    "\32\35\1\36\16\35\1\371\25\35\1\55\32\35\1\36"+
    "\35\35\1\372\6\35\1\55\32\35\1\36\34\35\1\373"+
    "\7\35\1\55\32\35\1\36\16\35\1\374\1\35\1\375"+
    "\10\35\1\376\12\35\1\55\26\35\23\0\1\377\135\0"+
    "\1\u0100\104\0\1\u0101\11\0\4\35\1\36\10\35\1\u0102"+
    "\33\35\1\55\32\35\1\36\32\35\1\u0103\11\35\1\55"+
    "\32\35\1\36\16\35\1\u0104\25\35\1\55\32\35\1\36"+
    "\20\35\1\u0105\15\35\1\u0106\1\u0107\4\35\1\55\32\35"+
    "\1\u0108\44\35\1\55\32\35\1\36\32\35\1\u0109\11\35"+
    "\1\55\32\35\1\36\44\35\1\55\1\35\1\u010a\30\35"+
    "\1\36\40\35\1\u010b\3\35\1\55\32\35\1\36\35\35"+
    "\1\u010c\6\35\1\55\32\35\1\36\35\35\1\u010d\6\35"+
    "\1\55\32\35\1\u010e\44\35\1\55\32\35\1\36\26\35"+
    "\1\u010f\15\35\1\55\32\35\1\36\22\35\1\u0110\21\35"+
    "\1\55\32\35\1\36\31\35\1\u0111\12\35\1\55\32\35"+
    "\1\36\34\35\1\u0112\7\35\1\55\32\35\1\36\37\35"+
    "\1\u0113\4\35\1\55\26\35\25\0\1\u0114\141\0\1\u0115"+
    "\74\0\1\u0116\13\0\4\35\1\u0117\44\35\1\55\32\35"+
    "\1\36\30\35\1\u0118\13\35\1\55\32\35\1\36\34\35"+
    "\1\u0119\7\35\1\55\32\35\1\36\32\35\1\u011a\11\35"+
    "\1\55\32\35\1\36\34\35\1\u011b\7\35\1\55\32\35"+
    "\1\36\35\35\1\u011c\6\35\1\55\32\35\1\36\31\35"+
    "\1\u011d\12\35\1\55\32\35\1\36\20\35\1\u011e\15\35"+
    "\1\u011f\1\u0120\4\35\1\55\32\35\1\36\26\35\1\u0121"+
    "\15\35\1\55\32\35\1\36\41\35\1\u0122\2\35\1\55"+
    "\32\35\1\36\44\35\1\55\1\35\1\u0123\30\35\1\36"+
    "\17\35\1\u0124\24\35\1\55\32\35\1\36\24\35\1\u0125"+
    "\17\35\1\55\32\35\1\36\36\35\1\u0126\5\35\1\55"+
    "\32\35\1\36\22\35\1\u0127\21\35\1\55\32\35\1\36"+
    "\22\35\1\u0128\21\35\1\55\26\35\33\0\1\u0129\134\0"+
    "\1\u012a\71\0\1\u012b\15\0\4\35\1\36\33\35\1\u012c"+
    "\10\35\1\55\32\35\1\36\26\35\1\u012d\15\35\1\55"+
    "\32\35\1\36\30\35\1\u012e\13\35\1\55\32\35\1\36"+
    "\26\35\1\u012f\15\35\1\55\32\35\1\36\37\35\1\u0130"+
    "\4\35\1\55\32\35\1\u0131\44\35\1\55\32\35\1\36"+
    "\32\35\1\u0132\11\35\1\55\32\35\1\36\34\35\1\u0133"+
    "\7\35\1\55\32\35\1\36\35\35\1\u0134\6\35\1\55"+
    "\32\35\1\36\16\35\1\u0135\25\35\1\55\32\35\1\36"+
    "\32\35\1\u0136\11\35\1\55\32\35\1\36\20\35\1\u0137"+
    "\15\35\1\u0138\5\35\1\55\32\35\1\36\27\35\1\u0139"+
    "\14\35\1\55\32\35\1\36\37\35\1\u013a\4\35\1\55"+
    "\32\35\1\36\26\35\1\u013b\15\35\1\55\32\35\1\36"+
    "\16\35\1\u013c\25\35\1\55\32\35\1\36\40\35\1\u013d"+
    "\3\35\1\55\26\35\37\0\1\u013e\116\0\1\u013f\102\0"+
    "\1\u0140\16\0\4\35\1\36\32\35\1\u0141\11\35\1\55"+
    "\32\35\1\36\32\35\1\u0142\11\35\1\55\32\35\1\36"+
    "\33\35\1\u0143\10\35\1\55\32\35\1\36\40\35\1\u0144"+
    "\3\35\1\55\32\35\1\36\16\35\1\u0145\25\35\1\55"+
    "\32\35\1\36\30\35\1\u0146\13\35\1\55\32\35\1\36"+
    "\26\35\1\u0147\15\35\1\55\32\35\1\36\37\35\1\u0148"+
    "\4\35\1\55\32\35\1\u0149\44\35\1\55\32\35\1\36"+
    "\34\35\1\u014a\7\35\1\55\32\35\1\36\32\35\1\u014b"+
    "\11\35\1\55\32\35\1\36\34\35\1\u014c\7\35\1\55"+
    "\32\35\1\36\22\35\1\u014d\21\35\1\55\32\35\1\36"+
    "\31\35\1\u014e\12\35\1\55\32\35\1\36\24\35\1\u014f"+
    "\17\35\1\55\32\35\1\36\20\35\1\u0150\23\35\1\55"+
    "\32\35\1\36\32\35\1\u0151\11\35\1\55\26\35\36\0"+
    "\1\u0152\114\0\1\u0153\3\0\1\u0154\75\0\1\u0155\22\0"+
    "\4\35\1\36\31\35\1\u0156\12\35\1\55\32\35\1\u0157"+
    "\44\35\1\55\32\35\1\36\32\35\1\u0158\11\35\1\55"+
    "\32\35\1\36\26\35\1\u0159\15\35\1\55\32\35\1\36"+
    "\34\35\1\u015a\7\35\1\55\32\35\1\36\33\35\1\u015b"+
    "\10\35\1\55\32\35\1\36\40\35\1\u015c\3\35\1\55"+
    "\32\35\1\36\16\35\1\u015d\25\35\1\55\32\35\1\36"+
    "\21\35\1\u015e\22\35\1\55\32\35\1\36\30\35\1\u015f"+
    "\13\35\1\55\32\35\1\36\26\35\1\u0160\15\35\1\55"+
    "\32\35\1\u0161\44\35\1\55\32\35\1\36\36\35\1\u0162"+
    "\5\35\1\55\32\35\1\36\37\35\1\u0163\4\35\1\55"+
    "\32\35\1\36\26\35\1\u0164\15\35\1\55\32\35\1\u0165"+
    "\44\35\1\55\26\35\76\0\1\u0166\66\0\1\u0167\100\0"+
    "\1\u0168\72\0\1\u0169\16\0\4\35\1\36\22\35\1\u016a"+
    "\21\35\1\55\32\35\1\36\31\35\1\u016b\12\35\1\55"+
    "\32\35\1\36\16\35\1\u016c\25\35\1\55\32\35\1\36"+
    "\26\35\1\u016d\15\35\1\55\32\35\1\36\32\35\1\u016e"+
    "\11\35\1\55\32\35\1\36\26\35\1\u016f\15\35\1\55"+
    "\32\35\1\36\34\35\1\u0170\7\35\1\55\32\35\1\u0171"+
    "\44\35\1\55\32\35\1\36\33\35\1\u0172\10\35\1\55"+
    "\32\35\1\36\40\35\1\u0173\3\35\1\55\32\35\1\36"+
    "\16\35\1\u0174\25\35\1\55\32\35\1\36\32\35\1\u0175"+
    "\11\35\1\55\32\35\1\36\32\35\1\u0176\11\35\1\55"+
    "\26\35\57\0\1\u0177\73\0\1\u0178\113\0\1\u0179\10\0"+
    "\4\35\1\36\31\35\1\u017a\12\35\1\55\32\35\1\36"+
    "\22\35\1\u017b\21\35\1\55\32\35\1\u017c\44\35\1\55"+
    "\32\35\1\36\32\35\1\u017d\11\35\1\55\32\35\1\36"+
    "\31\35\1\u017e\12\35\1\55\32\35\1\36\16\35\1\u017f"+
    "\25\35\1\55\32\35\1\36\26\35\1\u0180\15\35\1\55"+
    "\32\35\1\36\32\35\1\u0181\11\35\1\55\32\35\1\36"+
    "\26\35\1\u0182\15\35\1\55\32\35\1\u0183\44\35\1\55"+
    "\32\35\1\u0184\44\35\1\55\32\35\1\36\31\35\1\u0185"+
    "\12\35\1\55\26\35\54\0\1\u0186\110\0\1\u0187\102\0"+
    "\1\u0188\7\0\4\35\1\36\36\35\1\u0189\5\35\1\55"+
    "\32\35\1\36\31\35\1\u018a\12\35\1\55\32\35\1\u018b"+
    "\44\35\1\55\32\35\1\36\22\35\1\u018c\21\35\1\55"+
    "\32\35\1\u018d\44\35\1\55\32\35\1\36\32\35\1\u018e"+
    "\11\35\1\55\32\35\1\36\31\35\1\u018f\12\35\1\55"+
    "\32\35\1\36\16\35\1\u0190\25\35\1\55\32\35\1\u0191"+
    "\44\35\1\55\26\35\62\0\1\u0192\74\0\1\u0193\76\0"+
    "\1\u0194\21\0\4\35\1\36\22\35\1\u0195\21\35\1\55"+
    "\32\35\1\36\36\35\1\u0196\5\35\1\55\32\35\1\36"+
    "\31\35\1\u0197\12\35\1\55\32\35\1\u0198\44\35\1\55"+
    "\32\35\1\36\22\35\1\u0199\21\35\1\55\32\35\1\u019a"+
    "\44\35\1\55\26\35\61\0\1\u019b\72\0\1\u019c\102\0"+
    "\1\u019d\20\0\4\35\1\u019e\44\35\1\55\32\35\1\36"+
    "\22\35\1\u019f\21\35\1\55\32\35\1\36\36\35\1\u01a0"+
    "\5\35\1\55\32\35\1\36\31\35\1\u01a1\12\35\1\55"+
    "\26\35\73\0\1\u01a2\66\0\1\u01a3\103\0\1\u01a4\11\0"+
    "\4\35\1\u01a5\44\35\1\55\32\35\1\36\22\35\1\u01a6"+
    "\21\35\1\55\32\35\1\36\36\35\1\u01a7\5\35\1\55"+
    "\26\35\54\0\1\u01a8\104\0\1\u01a9\16\0\4\35\1\u01aa"+
    "\44\35\1\55\32\35\1\36\22\35\1\u01ab\21\35\1\55"+
    "\26\35\56\0\1\u01ac\114\0\1\u01ad\4\0\4\35\1\u01ae"+
    "\44\35\1\55\26\35\54\0\1\u01af\77\0\1\u01b0\101\0"+
    "\1\u01b1\75\0\1\u01b2\23\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[24064];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\7\11\1\1\1\11\1\1\2\11"+
    "\2\1\2\11\4\1\3\11\1\0\1\11\20\0\1\1"+
    "\2\11\30\0\1\1\15\0\1\11\24\0\1\11\55\0"+
    "\1\11\13\0\1\11\3\0\1\11\17\0\1\11\3\0"+
    "\1\11\6\0\1\11\2\0\1\11\10\0\1\11\24\0"+
    "\1\11\6\0\1\11\7\0\1\11\1\0\1\11\17\0"+
    "\1\11\5\0\1\11\10\0\1\11\31\0\1\11\27\0"+
    "\1\11\15\0\1\11\11\0\1\11\3\0\2\11\12\0"+
    "\1\11\12\0\1\11\6\0\2\11\6\0\1\11\1\0"+
    "\1\11\3\0\1\11\2\0\1\1\3\0\1\11\1\0"+
    "\1\11\3\0\1\11\5\0\2\11\4\0\1\11\3\0"+
    "\2\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[434];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    /*START-CODE*/
    private ArrayList<ReportErrorInterpreter> listError = new ArrayList();
  
    private void print(String token) {
        //System.out.println(" < " + yytext() + " > <Linea\"" + (yyline + 1) + "\">" + "<Columna\"" + (yycolumn+1) + "\">");
    }

    private void addError(){
        print("error");
        TypeIntreprete type = TypeIntreprete.LEXICON;
        Token toke = new Token(yyline + 1, yycolumn + 1, yytext());
        this.listError.add(new ReportErrorInterpreter(type, toke, ReportingConstants.ERROR_LEXEMA));
    }
    public ArrayList<ReportErrorInterpreter> getListError() {
        return this.listError;
    }

    /*FINAL-CODE*/


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexemaByMyParesUser(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {   return new java_cup.runtime.Symbol(MySymUser.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { //MANEJAR EL ERROR LEXICO
                        print("ERROR");
                        addError();
            }
          // fall through
          case 64: break;
          case 2:
            { /* print(); */
            }
          // fall through
          case 65: break;
          case 3:
            { print("("); return new Symbol(MySymUser.PARENTESIS_A,yyline,yycolumn,yytext());
            }
          // fall through
          case 66: break;
          case 4:
            { print(")"); return new Symbol(MySymUser.PARENTESIS_C,yyline,yycolumn,yytext());
            }
          // fall through
          case 67: break;
          case 5:
            { print("*"); return new Symbol(MySymUser.MULTIPLICAR,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 68: break;
          case 6:
            { print("+"); return new Symbol(MySymUser.SUMAR,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 69: break;
          case 7:
            { print(","); return new Symbol(MySymUser.COMA,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 70: break;
          case 8:
            { print("-"); return new Symbol(MySymUser.RESTAR,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 71: break;
          case 9:
            { print("/"); return new Symbol(MySymUser.DIVIDIR,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 72: break;
          case 10:
            { print("REAL_NUMEBERS"); return new Symbol(MySymUser.REAL_NUMEBERS ,yyline,yycolumn,yytext());
            }
          // fall through
          case 73: break;
          case 11:
            { print(":"); return new Symbol(MySymUser.COLNO,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 74: break;
          case 12:
            { print("<" ); return new Symbol(MySymUser.OPEN ,yyline,yycolumn,yytext());
            }
          // fall through
          case 75: break;
          case 13:
            { print("="); return new Symbol(MySymUser.EQUAL,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 76: break;
          case 14:
            { print(">" ); return new Symbol(MySymUser.CLOSE ,yyline,yycolumn,yytext());
            }
          // fall through
          case 77: break;
          case 15:
            { print("["); return new Symbol(MySymUser.BRACKETS_O ,yyline,yycolumn,yytext());
            }
          // fall through
          case 78: break;
          case 16:
            { print("]"); return new Symbol(MySymUser.BRACKETS_C ,yyline,yycolumn,yytext());
            }
          // fall through
          case 79: break;
          case 17:
            { print("{"); return new Symbol(MySymUser.KEYS_O ,yyline,yycolumn,yytext());
            }
          // fall through
          case 80: break;
          case 18:
            { print("}"); return new Symbol(MySymUser.KEYS_C ,yyline,yycolumn,yytext());
            }
          // fall through
          case 81: break;
          case 19:
            { print("!>" ); return new Symbol(MySymUser.CLOSE_REQUEST ,yyline,yycolumn,yytext());
            }
          // fall through
          case 82: break;
          case 20:
            { print("STRING"); return new Symbol(MySymUser.STRING ,yyline,yycolumn,yytext());
            }
          // fall through
          case 83: break;
          case 21:
            { print("<!" ); return new Symbol(MySymUser.OPEN_REQUEST ,yyline,yycolumn,yytext());
            }
          // fall through
          case 84: break;
          case 22:
            { print("<?" ); return new Symbol(MySymUser.OPEN_VERSION ,yyline,yycolumn,yytext());
            }
          // fall through
          case 85: break;
          case 23:
            { print("?>" ); return new Symbol(MySymUser.CLOSE_VERSION ,yyline,yycolumn,yytext());
            }
          // fall through
          case 86: break;
          case 24:
            { print("\"ID\""); return new Symbol(MySymUser.ID ,yyline,yycolumn,yytext());
            }
          // fall through
          case 87: break;
          case 25:
            { print("xson"); return new Symbol(MySymUser.XSON ,yyline,yycolumn,yytext());
            }
          // fall through
          case 88: break;
          case 26:
            { print("\"TEMA\""); return new Symbol(MySymUser.TEMA ,yyline,yycolumn,yytext());
            }
          // fall through
          case 89: break;
          case 27:
            { print("\"CLASE\""); return new Symbol(MySymUser.CLASE ,yyline,yycolumn,yytext());
            }
          // fall through
          case 90: break;
          case 28:
            { print("\"FILAS\""); return new Symbol(MySymUser.FILAS ,yyline,yycolumn,yytext());
            }
          // fall through
          case 91: break;
          case 29:
            { /*COMENTARIO*/
            }
          // fall through
          case 92: break;
          case 30:
            { print("version"); return new Symbol(MySymUser.VERSION ,yyline,yycolumn,yytext());
            }
          // fall through
          case 93: break;
          case 31:
            { print("\"INDICE\""); return new Symbol(MySymUser.INDICE ,yyline,yycolumn,yytext());
            }
          // fall through
          case 94: break;
          case 32:
            { print("\"NOMBRE\""); return new Symbol(MySymUser.NAME_PERSONAL_USER ,yyline,yycolumn,yytext());
            }
          // fall through
          case 95: break;
          case 33:
            { print("\"TRIVIA\""); return new Symbol(MySymUser.TRIVIA ,yyline,yycolumn,yytext());
            }
          // fall through
          case 96: break;
          case 34:
            { print("\"USUARIO\""); return new Symbol(MySymUser.NAME_USER ,yyline,yycolumn,yytext());
            }
          // fall through
          case 97: break;
          case 35:
            { print("\"COLUMNAS\""); return new Symbol(MySymUser.COLUMNAS ,yyline,yycolumn,yytext());
            }
          // fall through
          case 98: break;
          case 36:
            { print("\"OPCIONES\""); return new Symbol(MySymUser.OPCIONES ,yyline,yycolumn,yytext());
            }
          // fall through
          case 99: break;
          case 37:
            { print("\"PASSWORD\""); return new Symbol(MySymUser.PASS_USER ,yyline,yycolumn,yytext());
            }
          // fall through
          case 100: break;
          case 38:
            { print("\"ID_TRIVIA\""); return new Symbol(MySymUser.ID_TRIVIA ,yyline,yycolumn,yytext());
            }
          // fall through
          case 101: break;
          case 39:
            { print("\"RESPUESTA\""); return new Symbol(MySymUser.RESPUESTA ,yyline,yycolumn,yytext());
            }
          // fall through
          case 102: break;
          case 40:
            { print("DATE"); return new Symbol(MySymUser.STRING_DATE,yyline,yycolumn,yytext());
            }
          // fall through
          case 103: break;
          case 41:
            { print("INSTITUCION"); return new Symbol(MySymUser.INSTITUCION ,yyline,yycolumn,yytext());
            }
          // fall through
          case 104: break;
          case 42:
            { print("\"NUEVA_TRIVIA\""); return new Symbol(MySymUser.NEW_TRIVIA ,yyline,yycolumn,yytext());
            }
          // fall through
          case 105: break;
          case 43:
            { print("\"DATOS_USUARIO\""); return new Symbol(MySymUser.USER_DATA ,yyline,yycolumn,yytext());
            }
          // fall through
          case 106: break;
          case 44:
            { print("\"TEXTO_VISIBLE\""); return new Symbol(MySymUser.TEXTO_VISIBLE ,yyline,yycolumn,yytext());
            }
          // fall through
          case 107: break;
          case 45:
            { print("\"USUARIO_NUEVO\""); return new Symbol(MySymUser.NEW_USER ,yyline,yycolumn,yytext());
            }
          // fall through
          case 108: break;
          case 46:
            { print("FECHA_CREACION"); return new Symbol(MySymUser.DATE ,yyline,yycolumn,yytext());
            }
          // fall through
          case 109: break;
          case 47:
            { print("\"NUEVO_PASSWORD\""); return new Symbol(MySymUser.NUEVO_PASSWORD ,yyline,yycolumn,yytext());
            }
          // fall through
          case 110: break;
          case 48:
            { print("\"ELIMINAR_TRIVIA\""); return new Symbol(MySymUser.ELIMINAR_TRIVIA ,yyline,yycolumn,yytext());
            }
          // fall through
          case 111: break;
          case 49:
            { print("\"TIEMPO_PREGUNTA\""); return new Symbol(MySymUser.TIEMPO_PREGUNTA ,yyline,yycolumn,yytext());
            }
          // fall through
          case 112: break;
          case 50:
            { print("\"USUARIO_ANTIGUO\""); return new Symbol(MySymUser.USUARIO_ANTIGUO ,yyline,yycolumn,yytext());
            }
          // fall through
          case 113: break;
          case 51:
            { print("\"ELIMINAR_USUARIO\""); return new Symbol(MySymUser.ELIMINAR_USUARIO  ,yyline,yycolumn,yytext());
            }
          // fall through
          case 114: break;
          case 52:
            { print("\"MODIFICAR_TRIVIA\""); return new Symbol(MySymUser.MODIFICAR_TRIVIA ,yyline,yycolumn,yytext());
            }
          // fall through
          case 115: break;
          case 53:
            { print("\"USUARIO_CREACION\""); return new Symbol(MySymUser.USUARIO_CREACION ,yyline,yycolumn,yytext());
            }
          // fall through
          case 116: break;
          case 54:
            { print("realizar_solicitud"); return new Symbol(MySymUser.MAKE_REQUEST ,yyline,yycolumn,yytext());
            }
          // fall through
          case 117: break;
          case 55:
            { print("\"MODIFICAR_USUARIO\""); return new Symbol(MySymUser.MODIFICAR_USUARIO  ,yyline,yycolumn,yytext());
            }
          // fall through
          case 118: break;
          case 56:
            { print("\"PARAMETROS_TRIVIA\""); return new Symbol(MySymUser.PARAMETROS_TRIVIA ,yyline,yycolumn,yytext());
            }
          // fall through
          case 119: break;
          case 57:
            { print("\"AGREGAR_COMPONENTE\""); return new Symbol(MySymUser.AGREGAR_COMPONENTE ,yyline,yycolumn,yytext());
            }
          // fall through
          case 120: break;
          case 58:
            { print("realizar_solicitudes"); return new Symbol(MySymUser.MAKE_REQUESTS ,yyline,yycolumn,yytext());
            }
          // fall through
          case 121: break;
          case 59:
            { print("\"ELIMINAR_COMPONENTE\""); return new Symbol(MySymUser.ELIMINAR_COMPONENTE ,yyline,yycolumn,yytext());
            }
          // fall through
          case 122: break;
          case 60:
            { print("\"MODIFICAR_COMPONENTE\""); return new Symbol(MySymUser.MODIFICAR_COMPONENTE ,yyline,yycolumn,yytext());
            }
          // fall through
          case 123: break;
          case 61:
            { print("\"PARAMETROS_COMPONENTE\""); return new Symbol(MySymUser.PARAMETROS_COMPONENTE ,yyline,yycolumn,yytext());
            }
          // fall through
          case 124: break;
          case 62:
            { print("fin_solicitud_realizada"); return new Symbol(MySymUser.FINAL_REQUEST ,yyline,yycolumn,yytext());
            }
          // fall through
          case 125: break;
          case 63:
            { print("fin_solicitudes_realizada"); return new Symbol(MySymUser.FINAL_REQUESTS ,yyline,yycolumn,yytext());
            }
          // fall through
          case 126: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
