
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package LexicalAndSyntacticAnalyzer.jflexandcupSQLKV;

/** CUP generated class containing symbol constants. */
public class MySymSQLKV {
  /* terminals */
  public static final int MULTIPLICAR = 12;
  public static final int DIVIDIR = 11;
  public static final int AND = 30;
  public static final int TIEMPO_PREGUNTA = 21;
  public static final int REPORTE = 26;
  public static final int GREATER_THAN_OR_EQUAL = 4;
  public static final int OR = 31;
  public static final int FECHA_CREACION = 19;
  public static final int EQUAL = 6;
  public static final int GREATER_THAN = 2;
  public static final int REAL_NUMEBERS = 14;
  public static final int NOT = 32;
  public static final int SCORE = 24;
  public static final int POR = 28;
  public static final int FILTRAR = 27;
  public static final int TEMA = 22;
  public static final int COMA = 17;
  public static final int STRING = 7;
  public static final int NOMBRE = 18;
  public static final int EOF = 0;
  public static final int USUARIO_CREACION = 23;
  public static final int ID_TRIVIA = 8;
  public static final int INSTITUCION = 20;
  public static final int TIEMPO = 13;
  public static final int LESS_THAN = 3;
  public static final int RESTAR = 10;
  public static final int USUARIO = 29;
  public static final int PARENTESIS_C = 16;
  public static final int error = 1;
  public static final int PARENTESIS_A = 15;
  public static final int LESS_THAN_OR_EQUAL = 5;
  public static final int SUMAR = 9;
  public static final int SELECCIONAR = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GREATER_THAN",
  "LESS_THAN",
  "GREATER_THAN_OR_EQUAL",
  "LESS_THAN_OR_EQUAL",
  "EQUAL",
  "STRING",
  "ID_TRIVIA",
  "SUMAR",
  "RESTAR",
  "DIVIDIR",
  "MULTIPLICAR",
  "TIEMPO",
  "REAL_NUMEBERS",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "COMA",
  "NOMBRE",
  "FECHA_CREACION",
  "INSTITUCION",
  "TIEMPO_PREGUNTA",
  "TEMA",
  "USUARIO_CREACION",
  "SCORE",
  "SELECCIONAR",
  "REPORTE",
  "FILTRAR",
  "POR",
  "USUARIO",
  "AND",
  "OR",
  "NOT"
  };
}

