package LexicalAndSyntacticAnalyzer;

public enum ListRequests {
    //user
    NEW_USER,LOGIN_USER,MODIFICAR_USUARIO,ELIMINAR_USUARIO,
    //trivia
    NEW_TRIVIA,MODIFICAR_TRIVIA,ELIMINAR_TRIVIA,
    //component
    AGREGAR_COMPONENTE,MODIFICAR_COMPONENTE,ELIMINAR_COMPONENTE,
    //
    QUIZATTEMPT
    ;
}
