
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package LexicalAndSyntacticAnalyzer.jflexandcupDataBaseTrivias;

/** CUP generated class containing symbol constants. */
public class MySymLoginDataBaseTrivias {
  /* terminals */
  public static final int COLNO = 15;
  public static final int MULTIPLICAR = 6;
  public static final int DIVIDIR = 5;
  public static final int ID_COMPONENT = 24;
  public static final int COLUMN = 30;
  public static final int DATE = 22;
  public static final int REAL_NUMEBERS = 9;
  public static final int STRING_DATE = 10;
  public static final int BRACKETS_O = 11;
  public static final int NAME = 18;
  public static final int ID_USER = 21;
  public static final int ROW = 29;
  public static final int ID = 17;
  public static final int KEYS_O = 13;
  public static final int THEME = 20;
  public static final int TYPE = 25;
  public static final int STRING = 2;
  public static final int COMA = 16;
  public static final int BRACKETS_C = 12;
  public static final int EOF = 0;
  public static final int ID_TRIVIA = 32;
  public static final int TIME = 19;
  public static final int KEYS_C = 14;
  public static final int STRUCTURE = 23;
  public static final int RESTAR = 4;
  public static final int PARENTESIS_C = 8;
  public static final int error = 1;
  public static final int PARENTESIS_A = 7;
  public static final int OPTIONS = 28;
  public static final int TEXT = 27;
  public static final int SUMAR = 3;
  public static final int INDEX = 26;
  public static final int RESULT = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRING",
  "SUMAR",
  "RESTAR",
  "DIVIDIR",
  "MULTIPLICAR",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "REAL_NUMEBERS",
  "STRING_DATE",
  "BRACKETS_O",
  "BRACKETS_C",
  "KEYS_O",
  "KEYS_C",
  "COLNO",
  "COMA",
  "ID",
  "NAME",
  "TIME",
  "THEME",
  "ID_USER",
  "DATE",
  "STRUCTURE",
  "ID_COMPONENT",
  "TYPE",
  "INDEX",
  "TEXT",
  "OPTIONS",
  "ROW",
  "COLUMN",
  "RESULT",
  "ID_TRIVIA"
  };
}

