
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package jflexandcup;

/** CUP generated class containing symbol constants. */
public class MySymLoginUser {
  /* terminals */
  public static final int COLNO = 7;
  public static final int MULTIPLICAR = 14;
  public static final int DIVIDIR = 13;
  public static final int NAME_PERSONAL_USER = 31;
  public static final int CLOSE = 8;
  public static final int EQUAL = 2;
  public static final int REAL_NUMEBERS = 15;
  public static final int FINAL_REQUEST = 23;
  public static final int XSON = 5;
  public static final int BRACKETS_O = 18;
  public static final int CLOSE_REQUEST = 24;
  public static final int CLOSE_VERSION = 4;
  public static final int KEYS_O = 20;
  public static final int COMA = 26;
  public static final int STRING = 10;
  public static final int BRACKETS_C = 19;
  public static final int EOF = 0;
  public static final int PASS_USER = 30;
  public static final int INSTITUCION = 32;
  public static final int KEYS_C = 21;
  public static final int RESTAR = 12;
  public static final int USER_DATA = 28;
  public static final int PARENTESIS_C = 17;
  public static final int error = 1;
  public static final int NAME_USER = 29;
  public static final int PARENTESIS_A = 16;
  public static final int OPEN_REQUEST = 22;
  public static final int MAKE_REQUEST = 25;
  public static final int VERSION = 6;
  public static final int OPEN_VERSION = 3;
  public static final int OPEN = 9;
  public static final int SUMAR = 11;
  public static final int NEW_USER = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EQUAL",
  "OPEN_VERSION",
  "CLOSE_VERSION",
  "XSON",
  "VERSION",
  "COLNO",
  "CLOSE",
  "OPEN",
  "STRING",
  "SUMAR",
  "RESTAR",
  "DIVIDIR",
  "MULTIPLICAR",
  "REAL_NUMEBERS",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "BRACKETS_O",
  "BRACKETS_C",
  "KEYS_O",
  "KEYS_C",
  "OPEN_REQUEST",
  "FINAL_REQUEST",
  "CLOSE_REQUEST",
  "MAKE_REQUEST",
  "COMA",
  "NEW_USER",
  "USER_DATA",
  "NAME_USER",
  "PASS_USER",
  "NAME_PERSONAL_USER",
  "INSTITUCION"
  };
}

